// Shared mock data — in production this comes from the FastAPI /api/products endpoint

export interface Product {
  id: number
  title: string
  description: string
  price: number
  image_url: string
  category: string
  rating: number
  review_count: number
  badge?: string
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: 'Chronos Elite Watch',
    description: 'Soft gold accents with a hand-stitched leather strap and automatic movement.',
    price: 4950.00,
    image_url: '/images/chronos_elite.jpg',
    category: 'Luxury Watch',
    rating: 4.9,
    review_count: 142,
    badge: 'Soft Gold Accents',
  },
  {
    id: 2,
    title: 'Aura Headphones',
    description: 'Sleek over-ear audio with custom acoustic profile and hybrid active noise cancellation.',
    price: 850.00,
    image_url: '/images/aura_headphones.jpg',
    category: 'Premium Audio',
    rating: 4.8,
    review_count: 98,
    badge: 'Product Shot',
  },
  {
    id: 3,
    title: 'Aria Crossbody',
    description: 'Handcrafted calfskin leather crossbody bag with structured metal hardware.',
    price: 1200.00,
    image_url: '/images/aria_crossbody.jpg',
    category: 'Designer Bags',
    rating: 4.7,
    review_count: 64,
    badge: 'Designer',
  },
  {
    id: 4,
    title: 'Modern Essential Blazer',
    description: 'Minimalist double-breasted structured blazer in premium wool blend.',
    price: 950.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 4.6,
    review_count: 53,
    badge: 'Curated Look',
  },
  {
    id: 5,
    title: 'Voyager Leather Duffle',
    description: 'Spacious weekender bag crafted from water-resistant pebble-grain leather.',
    price: 1650.00,
    image_url: '/images/voyager_duffle.png',
    category: 'Designer Bags',
    rating: 4.8,
    review_count: 36,
    badge: 'Travel Premium',
  },
  {
    id: 6,
    title: 'Eclipse Sunglasses',
    description: 'Classic tortoiseshell frame with lightweight polarized Carl Zeiss lenses.',
    price: 420.00,
    image_url: '/images/eclipse_sunglasses.png',
    category: 'Accessories',
    rating: 4.5,
    review_count: 112,
    badge: 'Limited Edition',
  },
  {
    id: 7,
    title: 'Apex Smartwatch',
    description: 'Sapphire glass screen with brushed titanium frame and real-time heart metrics.',
    price: 2499.00,
    image_url: '/images/apex_smartwatch.png',
    category: 'Luxury Watch',
    rating: 4.7,
    review_count: 85,
    badge: 'New Release',
  },
  {
    id: 8,
    title: 'Sartorial Trench Coat',
    description: 'Bespoke cotton-gabardine storm coat with signature horn buttons.',
    price: 1850.00,
    image_url: '/images/sartorial_trench.png',
    category: 'Curated Looks',
    rating: 4.9,
    review_count: 24,
    badge: 'Premium Selection',
  },
  {
    id: 9,
    title: 'Quantum Pro Laptop',
    description: 'Supercharged 16-inch workstation with liquid-cooled chip and premium anodized obsidian finish.',
    price: 2499.00,
    image_url: '/images/quantum_laptop.png',
    category: 'Electronics',
    rating: 4.9,
    review_count: 73,
    badge: 'Workstation',
  },
  {
    id: 10,
    title: 'AeroPhone 15 Pro',
    description: 'Brushed titanium smartphone with high-fidelity triple camera and 120Hz ceramic screen.',
    price: 1299.00,
    image_url: '/images/aerophone.png',
    category: 'Electronics',
    rating: 4.8,
    review_count: 124,
    badge: 'Best Seller',
  },
  {
    id: 11,
    title: 'Nomad Mechanical Keyboard',
    description: 'Machined aluminum gasket-mount keyboard with silent linear switches and custom gold keycaps.',
    price: 350.00,
    image_url: '/images/nomad_keyboard.png',
    category: 'Electronics',
    rating: 4.7,
    review_count: 42,
    badge: 'Premium Build',
  },
  {
    id: 12,
    title: 'Studio Reference Monitor',
    description: 'Active bi-amplified studio monitor with beryllium dome tweeter and carbon fiber woofer.',
    price: 1800.00,
    image_url: '/images/aura_headphones.jpg',
    category: 'Premium Audio',
    rating: 4.9,
    review_count: 19,
    badge: 'Pro Audio',
  },
  {
    id: 13,
    title: 'Verge Wireless Earbuds',
    description: 'Ultra-compact true wireless earbuds with custom adaptive audio tuning and secure fit.',
    price: 299.00,
    image_url: '/images/aura_headphones.jpg',
    category: 'Premium Audio',
    rating: 4.6,
    review_count: 88,
  },
  {
    id: 14,
    title: 'Stratus Knit Sneakers',
    description: 'Ultra-breathable recycled knit upper with responsive foam cushioning for all-day comfort.',
    price: 220.00,
    image_url: '/images/stratus_sneakers.png',
    category: 'Footwear',
    rating: 4.5,
    review_count: 94,
    badge: 'Trending',
  },
  {
    id: 15,
    title: 'Sovereign Chelsea Boots',
    description: 'Italian suede chelsea boots with elastic side panels and durable Goodyear-welted crepe soles.',
    price: 650.00,
    image_url: '/images/chelsea_boots.png',
    category: 'Footwear',
    rating: 4.7,
    review_count: 41,
    badge: 'Handcrafted',
  },
  {
    id: 16,
    title: 'Monarch Leather Loafers',
    description: 'Polished full-grain leather penny loafers with hand-stitched detailing and padded footbeds.',
    price: 480.00,
    image_url: '/images/chelsea_boots.png',
    category: 'Footwear',
    rating: 4.8,
    review_count: 32,
  },
  {
    id: 17,
    title: 'Apex Court High-Tops',
    description: 'Retro-inspired premium leather high-top sneakers with gold-accented eyelets.',
    price: 280.00,
    image_url: '/images/stratus_sneakers.png',
    category: 'Footwear',
    rating: 4.6,
    review_count: 67,
  },
  {
    id: 18,
    title: 'Luxe Cashmere Hoodie',
    description: 'Knit from 100% Mongolian cashmere with a relaxed fit and gold-tipped drawstrings.',
    price: 580.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 4.9,
    review_count: 38,
    badge: 'Cashmere',
  },
  {
    id: 19,
    title: 'Savile Row Dinner Suit',
    description: 'Bespoke double-breasted tux in midnight navy with satin peak lapels.',
    price: 2800.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 5.0,
    review_count: 12,
    badge: 'Bespoke',
  },
  {
    id: 20,
    title: 'Classic Linen Shirt',
    description: 'Breathable Italian linen shirt with a tailored fit, perfect for warm coastal evenings.',
    price: 180.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 4.4,
    review_count: 49,
  },
  {
    id: 21,
    title: 'Merino Wool Mockneck',
    description: 'Fine-gauge merino wool sweater with ribbed collar and cuffs, exceptionally soft.',
    price: 240.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 4.7,
    review_count: 57,
  },
  {
    id: 22,
    title: 'Park Avenue Leather Jacket',
    description: 'Buttery soft lambskin leather bomber jacket with custom gold zippers and silk lining.',
    price: 1450.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Curated Looks',
    rating: 4.9,
    review_count: 22,
    badge: 'Limited',
  },
  {
    id: 23,
    title: 'Vanguard Briefcase',
    description: 'Structured saffiano leather briefcase with padded laptop sleeve and combination lock.',
    price: 980.00,
    image_url: '/images/vanguard_briefcase.png',
    category: 'Designer Bags',
    rating: 4.8,
    review_count: 29,
  },
  {
    id: 24,
    title: 'Summit Rolltop Backpack',
    description: 'Water-resistant canvas backpack with leather straps and solid brass quick-release clips.',
    price: 850.00,
    image_url: '/images/rolltop_backpack.png',
    category: 'Designer Bags',
    rating: 4.7,
    review_count: 48,
  },
  {
    id: 25,
    title: 'Metro Leather Cardholder',
    description: 'Slim pebble-grain leather card wallet with 4 slots and a central bill pocket.',
    price: 150.00,
    image_url: '/images/vanguard_briefcase.png',
    category: 'Accessories',
    rating: 4.6,
    review_count: 105,
  },
  {
    id: 26,
    title: 'Submariner Prestige Watch',
    description: 'Classic diving watch with ceramic bezel, luminous markers, and oystersteel band.',
    price: 8500.00,
    image_url: '/images/chronos_elite.jpg',
    category: 'Luxury Watch',
    rating: 4.9,
    review_count: 211,
    badge: 'Collector Choice',
  },
  {
    id: 27,
    title: 'Grand Tourer Chrono Watch',
    description: 'Racing-inspired chronograph watch with carbon fiber dial and black rubber racing strap.',
    price: 3200.00,
    image_url: '/images/chronos_elite.jpg',
    category: 'Luxury Watch',
    rating: 4.7,
    review_count: 62,
  },
  {
    id: 28,
    title: 'Heritage Dress Watch',
    description: 'Ultra-thin 18k rose gold dress watch with manual wind and subsecond dial.',
    price: 6200.00,
    image_url: '/images/chronos_elite.jpg',
    category: 'Luxury Watch',
    rating: 4.8,
    review_count: 31,
  },
  {
    id: 29,
    title: 'Atlas Brass Cuff',
    description: 'Minimalist solid brass wrist cuff with hand-engraved geometric telemetry patterns.',
    price: 280.00,
    image_url: '/images/aria_crossbody.jpg',
    category: 'Accessories',
    rating: 4.5,
    review_count: 39,
  },
  {
    id: 30,
    title: 'Nomad Wool Scarf',
    description: 'Over-sized knit scarf in pure extrafine wool with classic fringed borders.',
    price: 190.00,
    image_url: '/images/modern_essential.jpg',
    category: 'Accessories',
    rating: 4.7,
    review_count: 73,
  },
  {
    id: 31,
    title: 'Optic Blue-Light Glasses',
    description: 'Acetate frame glasses with blue-light filtering lenses for digital console sessions.',
    price: 240.00,
    image_url: '/images/eclipse_sunglasses.png',
    category: 'Accessories',
    rating: 4.6,
    review_count: 55,
  },
  {
    id: 32,
    title: 'Royal Silk Kurta',
    description: 'Hand-loomed raw silk Kurta in deep gold with intricate embroidery around the collar.',
    price: 380.00,
    image_url: '/images/royal_silk_kurta.png',
    category: 'Curated Looks',
    rating: 4.8,
    review_count: 36,
    badge: 'Festive Selection',
  },
  {
    id: 33,
    title: 'Sovereign Nehru Jacket',
    description: 'Bespoke textured Nehru jacket with gold-plated brass buttons, designed to layer over kurtas.',
    price: 420.00,
    image_url: '/images/nehru_jacket.png',
    category: 'Curated Looks',
    rating: 4.7,
    review_count: 29,
    badge: 'Classic Layer',
  },
  {
    id: 34,
    title: 'Heritage Sherwani',
    description: 'Luxury embroidered Sherwani coat crafted from fine jacquard silk with traditional motifs.',
    price: 1250.00,
    image_url: '/images/royal_silk_kurta.png',
    category: 'Curated Looks',
    rating: 4.9,
    review_count: 14,
    badge: 'Bridal Selection',
  },
]

export const CATEGORIES = ['All', 'Luxury Watch', 'Premium Audio', 'Designer Bags', 'Curated Looks', 'Accessories', 'Electronics', 'Footwear']


